### ISSUE TITLE
Add OWIN adapter for Microsoft.AspNet.WebApi.Owin

### ISSUE THREAD

**Issue by panesofglass** [frank-fs/frank#44]
This could fix #37. See https://wizardsofsmart.wordpress.com/2014/11/26/working-with-non-compliant-owin-middleware/

**Comment by PleaseTwo** [comment]
Link doesn't work https://wizardsofsmart.azurewebsites.net/samples/working-with-non-compliant-owin-middleware/ . Please, fix it.

**Comment by panesofglass** [comment]
Updated
