### ISSUE TITLE
Re-purpose as helper library for Azure Functions

### ISSUE THREAD

**Issue by panesofglass** [frank-fs/frank#47]
I'm considering re-purposing this library to primarily work with [Azure Functions](https://azure.microsoft.com/en-us/documentation/articles/functions-reference-fsharp/). The HTTP Azure Function templates use the `System.Net.Http` types `HttpRequestMessage` and `HttpResponseMessage`, which Frank also uses. This makes Frank a natural option to build HTTP Azure Functions in F#. Perhaps this will breathe new life into this little library.

@enricosada, would you mind helping me work through this transition?

**Comment by enricosada** [comment]
I can send a pr with netcore, no problem. 

But azure functions use net46. The project.json is used only for packages

**Comment by panesofglass** [comment]
@enricosada thanks! I changed the title of this issue.

**Comment by enricosada** [comment]
@panesofglass i think is easier like that, no barrier to contribute, is just normal .net and f#

**Comment by panesofglass** [comment]
Gotcha. Then perhaps I should just fix the build. :)
